---
title: "Covenant of Majors"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
```

Column {data-width=650}
-----------------------------------------------------------------------

### Benchmarking de la implementación de politicas sustentables 

En este trabajo analizaremos que tan bien o que tan malo es el desempeño de los intendentes del municipio (las acciones conjuntas que llevan adelante los municipios de Gc Guaymayen, etc)

```{r}
co2 <- rnorm(50,200,30)
hist(co2)
```

Column {data-width=350}
-----------------------------------------------------------------------

### Participacion de cada municipio

```{r}
muni <- c("Capital","Godoy Cruz", "Guaymayen", "Maipu", "Lujan", "Las Heras")
munico2 <- c(300, 250, 270, 320, 412, 330)
pie(munico2, labels =(muni))

```

### Transporte público

```{r}

```
RSU (Residuos Sólidos Urbanos) 
====
```{r}

```


Reciclado 
====
  
  
```{r}

```

RAEE (Residuos de Aparatos eléctricos y electronicos) 
====

  
```{r}

```
Benchmarking de Intendentes
===
